// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPIueN0HEXEXLSxrl5qnkJvMszkYuHrRU',
    appId: '1:953808737818:web:822b5eede078904cc963a3',
    messagingSenderId: '953808737818',
    projectId: 'flutter-login-test-cc0c7',
    authDomain: 'flutter-login-test-cc0c7.firebaseapp.com',
    storageBucket: 'flutter-login-test-cc0c7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYVuDZGJukQBEaE2GzMnkc3ub-8wPNk-I',
    appId: '1:953808737818:android:508a5b5de9e1dda4c963a3',
    messagingSenderId: '953808737818',
    projectId: 'flutter-login-test-cc0c7',
    storageBucket: 'flutter-login-test-cc0c7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoGLuWHlWH1YBOJY1hVRiryj7N-AP0DlQ',
    appId: '1:953808737818:ios:93f792106c52d12dc963a3',
    messagingSenderId: '953808737818',
    projectId: 'flutter-login-test-cc0c7',
    storageBucket: 'flutter-login-test-cc0c7.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoGLuWHlWH1YBOJY1hVRiryj7N-AP0DlQ',
    appId: '1:953808737818:ios:93f792106c52d12dc963a3',
    messagingSenderId: '953808737818',
    projectId: 'flutter-login-test-cc0c7',
    storageBucket: 'flutter-login-test-cc0c7.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPIueN0HEXEXLSxrl5qnkJvMszkYuHrRU',
    appId: '1:953808737818:web:330ed69306ed6a37c963a3',
    messagingSenderId: '953808737818',
    projectId: 'flutter-login-test-cc0c7',
    authDomain: 'flutter-login-test-cc0c7.firebaseapp.com',
    storageBucket: 'flutter-login-test-cc0c7.firebasestorage.app',
  );
}
